== 2026-09-22

* Raised a request to CyberArk team to check on the ECAR DB connection issue.
* Made a Excel for status of all branches in all get repos we have in ecar and welcome
* Connected with naveen to understand story on CI/CD jenkins sanity check for git public -> private. 
  Felt that i need to know GITHUB APP a little
* Executed 2 unity requests in ASB1 and asked BAs to check

== 2026-09-28

* AUTOSYS - Morning check
** BDR:
Domain -> base clients -> clients -> consult -> click f1 key -> double click any row.
 
** SIR:
fund -> consult -> fund -> search -> click any row -> data should be present.

** Jeflin notes:
*** Early morning checks
**** Autosys job checks: search BDTT and polling jobs and mark all of them as successful.
**** For non-success jobs, terminate them first, then mark them as successful.

*** 9:30 AM
**** Check polling jobs in Autosys dev (Ho3, Lo3, To3) and prod.
**** Polling jobs should be in running (start jobs) or success (stop jobs) status, and the start date should be today's date.
**** For failing polling jobs, mark them as successful.
**** If polling jobs are already successful, force-start them.
